//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCM.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csdpEntities : DbContext
    {
        public csdpEntities()
            : base("name=csdpEntities")
        {
            this.Database.Connection.ConnectionString += ";password=BJt$aoZ^*rYDzicI$sW%gRiZTi8xT987NJRfwU^w;";
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cscm> cscm { get; set; }
        public virtual DbSet<cscmVersion> cscmVersion { get; set; }
        public virtual DbSet<authority> authority { get; set; }
    }
}
