//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCMPackage
    {
        public string id { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public string introduction { get; set; }
        public string description { get; set; }
        public string lastModifyTime { get; set; }
        public string registry { get; set; }
        public string auth { get; set; }
    }
}
