//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class CSCMDependencies
    {
        public string id { get; set; }
        public string packageId { get; set; }
        public string name { get; set; }
        public string version { get; set; }
        public string type { get; set; }
        public string state { get; set; }
        public string descriptioin { get; set; }
        public string message0 { get; set; }
        public string componentType { get; set; }
        public string lastModifyTime { get; set; }
    }
}
